# Generated by Django 4.2.4 on 2023-08-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
