# Generated by Django 4.2.4 on 2023-08-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_photos_image_photos_fifthimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='secondfimage',
            new_name='secondimage',
        ),
    ]
