# Generated by Django 4.2.4 on 2023-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_signuppage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuppage',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='username',
            field=models.CharField(blank=b'I01\n', max_length=20, null=True, unique=True),
        ),
    ]
