# Generated by Django 4.2.4 on 2023-08-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_compose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compose',
            new_name='composes',
        ),
    ]
