# Generated by Django 4.2.4 on 2023-08-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
